### ISSUE TITLE
Python2/python3

### ISSUE THREAD

**Issue by IsabelJimenez99** [verlab/Structural_Reasoning_SRR#3]
I tried to run the code following the steps but when I extract the features I ask for python2, but then the train and test code is with python3, is it a bug or do I have to create 2 different environments?

**Comment by eduardoatr** [comment]
No, definitely that's not a bug, it's a feature 🤣. If I remember correctly, all the models used to extract the attributes are developed in Python 2 (you can check the links), so I kept everything as close as possible to the original implementations for reproducibility. Now for my own project, I've decided to employ more modern tools, such as DGL, which require Python 3, and that's why we have two different versions in there. Anyway, you can change the extraction code as you wish, just keep in mind that it may cause undesired side effects in the final feature vectors.
